# Generated by Django 3.2 on 2021-04-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
