# Generated by Django 3.2 on 2021-04-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_endereco_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='endereco_principal',
            field=models.BooleanField(default=False, verbose_name='Endereço principal'),
        ),
    ]
