# Generated by Django 3.2 on 2021-04-12 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_endereco_endereco_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='endereco_cliente', to='cadastros.cliente', verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
