# Generated by Django 3.2 on 2021-04-23 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_auto_20210419_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='active',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='user',
        ),
    ]
