# Generated by Django 3.2 on 2021-04-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_auto_20210423_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='descricao',
            field=models.CharField(default='', max_length=50, verbose_name='descrição do endereço'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.CharField(max_length=8, unique=True, verbose_name='rg'),
        ),
    ]
